### ISSUE TITLE
More information on heat lists

### ISSUE THREAD

**Issue by tclare95** [AntonyM71/AEMS#35]
**Euro Open Requirement**

As a paddler who has entered multiple categories, I want to see which category I am paddling in a given heat.

IE:

JD entered K1, C1, OC1 (different events) Heat list should display:

bib# name event

In future, this could be expanded so an event could have associated information:

Event "EK1JM"
Category: K1
Age Group: Junior
Competition Level: Elite

**Comment by AntonyM71** [comment]
This seems like a sensible thing to add.

Later expansion of event metadata should be easy, open-close principle etc.

**Comment by AntonyM71** [comment]
If you're rebuilding the aemsAPI,  unfortunately this line of `buildAPI.sh` doesn't work on non-macOS systems

```
sed -i '' 's/\| any/ /g' src/redux/services/aemsApi.ts
```

You can use find and replace to just get rid of any `| any` entries in the autogenerated code.
